//! Logic, maths, plain values and output.

use super::super::{Category::*, Code, Kind, PinType::*, Prec};
use super::*;

pub(super) const KINDS: &[Kind] = &[
    // Logic.
    node(
        "is_valid",
        "Is Valid",
        Logic,
        pins![wired("Value", Any)],
        pins![wired("Result", Bool)],
        expression("{Value} ~= nil", Prec::Compare),
    ),
    node(
        "not",
        "Not",
        Logic,
        pins![literal("Value", Bool, "false")],
        pins![wired("Result", Bool)],
        expression("not {Value}", Prec::Unary),
    ),
    binary("and", "And", Logic, Bool, Bool, "{A} and {B}", Prec::And),
    binary("or", "Or", Logic, Bool, Bool, "{A} or {B}", Prec::Or),
    binary(
        "equal",
        "Equal",
        Logic,
        Any,
        Bool,
        "{A} == {B}",
        Prec::Compare,
    ),
    binary(
        "not_equal",
        "Not Equal",
        Logic,
        Any,
        Bool,
        "{A} ~= {B}",
        Prec::Compare,
    ),
    binary(
        "greater",
        "Greater Than",
        Logic,
        Number,
        Bool,
        "{A} > {B}",
        Prec::Compare,
    ),
    binary(
        "less",
        "Less Than",
        Logic,
        Number,
        Bool,
        "{A} < {B}",
        Prec::Compare,
    ),
    binary(
        "at_least",
        "At Least",
        Logic,
        Number,
        Bool,
        "{A} >= {B}",
        Prec::Compare,
    ),
    binary(
        "at_most",
        "At Most",
        Logic,
        Number,
        Bool,
        "{A} <= {B}",
        Prec::Compare,
    ),
    node(
        "select",
        "Select",
        Logic,
        pins![
            literal("Condition", Bool, "false"),
            literal("True", Any, "nil"),
            literal("False", Any, "nil"),
        ],
        pins![wired("Result", Any)],
        expression("if {Condition} then {True} else {False}", Prec::Or),
    ),
    // Math.
    binary("add", "Add", Math, Number, Number, "{A} + {B}", Prec::Add),
    binary(
        "subtract",
        "Subtract",
        Math,
        Number,
        Number,
        "{A} - {B}",
        Prec::Add,
    ),
    binary(
        "multiply",
        "Multiply",
        Math,
        Number,
        Number,
        "{A} * {B}",
        Prec::Mul,
    ),
    binary(
        "divide",
        "Divide",
        Math,
        Number,
        Number,
        "{A} / {B}",
        Prec::Mul,
    ),
    binary(
        "modulo",
        "Modulo",
        Math,
        Number,
        Number,
        "{A} % {B}",
        Prec::Mul,
    ),
    binary(
        "power",
        "Power",
        Math,
        Number,
        Number,
        "{A} ^ {B}",
        Prec::Pow,
    ),
    binary(
        "min",
        "Min",
        Math,
        Number,
        Number,
        "math.min({A}, {B})",
        Prec::Atom,
    ),
    binary(
        "max",
        "Max",
        Math,
        Number,
        Number,
        "math.max({A}, {B})",
        Prec::Atom,
    ),
    node(
        "clamp",
        "Clamp",
        Math,
        pins![
            literal("Value", Number, "0"),
            literal("Min", Number, "0"),
            literal("Max", Number, "1"),
        ],
        pins![wired("Result", Number)],
        expression("math.clamp({Value}, {Min}, {Max})", Prec::Atom),
    ),
    node(
        "abs",
        "Absolute",
        Math,
        pins![literal("Value", Number, "0")],
        pins![wired("Result", Number)],
        expression("math.abs({Value})", Prec::Atom),
    ),
    node(
        "round",
        "Round",
        Math,
        pins![literal("Value", Number, "0")],
        pins![wired("Result", Number)],
        expression("math.round({Value})", Prec::Atom),
    ),
    node(
        "negate",
        "Negate",
        Math,
        pins![literal("Value", Number, "0")],
        pins![wired("Result", Number)],
        expression("-{Value}", Prec::Unary),
    ),
    node(
        "random",
        "Random",
        Math,
        pins![literal("Min", Number, "1"), literal("Max", Number, "10")],
        pins![wired("Result", Number)],
        call("math.random({Min}, {Max})"),
    ),
    // Values.
    node(
        "number",
        "Number",
        Values,
        pins![literal("Value", Number, "0")],
        pins![wired("Result", Number)],
        expression("{Value}", Prec::Atom),
    ),
    node(
        "string",
        "String",
        Values,
        pins![literal("Value", String, "")],
        pins![wired("Result", String)],
        expression("{Value}", Prec::Atom),
    ),
    node(
        "boolean",
        "Boolean",
        Values,
        pins![literal("Value", Bool, "true")],
        pins![wired("Result", Bool)],
        expression("{Value}", Prec::Atom),
    ),
    node(
        "instance",
        "Instance Path",
        Values,
        pins![literal("Path", Instance, "workspace")],
        pins![wired("Instance", Instance)],
        expression("{Path}", Prec::Atom),
    ),
    binary(
        "join",
        "Join Text",
        Values,
        String,
        String,
        "{A} .. {B}",
        Prec::Concat,
    ),
    node(
        "to_string",
        "To String",
        Values,
        pins![literal("Value", Any, "nil")],
        pins![wired("Result", String)],
        expression("tostring({Value})", Prec::Atom),
    ),
    node(
        "to_number",
        "To Number",
        Values,
        pins![literal("Value", Any, "nil")],
        pins![wired("Result", Number)],
        expression("tonumber({Value})", Prec::Atom),
    ),
    node(
        "vector3",
        "Vector3",
        Values,
        pins![
            literal("X", Number, "0"),
            literal("Y", Number, "0"),
            literal("Z", Number, "0"),
        ],
        pins![wired("Vector", Any)],
        expression("Vector3.new({X}, {Y}, {Z})", Prec::Atom),
    ),
    node(
        "color3",
        "Color From RGB",
        Values,
        pins![
            literal("R", Number, "255"),
            literal("G", Number, "255"),
            literal("B", Number, "255"),
        ],
        pins![wired("Color", Any)],
        expression("Color3.fromRGB({R}, {G}, {B})", Prec::Atom),
    ),
    node(
        "count",
        "Count",
        Values,
        pins![wired("List", List)],
        pins![wired("Count", Number)],
        expression("#{List}", Prec::Unary),
    ),
    // Output.
    node(
        "print",
        "Print",
        Output,
        pins![IN, literal("Value", Any, "\"Hello\"")],
        pins![THEN],
        Code::Statement("print({Value})"),
    ),
    node(
        "warn",
        "Warn",
        Output,
        pins![IN, literal("Value", Any, "\"Warning\"")],
        pins![THEN],
        Code::Statement("warn({Value})"),
    ),
];
